Feature/naviga id mock pem keys
navigacontentlab/panurge pull request #1
Opened 2022-05-30 10:05 UTC by marcusarnemonaviga

took patch from butbucket repo of naviga id mock pem key feature, applied to this repo

2022-06-09 07:35 UTC, hugowetterberg requested changes

2022-06-09 07:35 UTC, hugowetterberg commented on navigaid/access_test_server.go
> -func NewMockService(opts MockServerOptions) (*http.ServeMux, *rsa.PrivateKey, error) {
I would say that more than two return values should be avoided. Sometimes it's justified to go up to three, but "never" more. The readability quickly starts to suffer, and one often ends up with a lot of blanking like on https://github.com/navigacontentlab/panurge/pull/1/files#diff-20147bea1b2dfcc4f9599689db4017a4fa2fe56fc6e33f514d562163e599d5e6L66

As we're changing the function signature we should take the opportunity to fold the non-error return values into a struct `MockService{Mux, PrivateKey, KeyID}`, if it also implements http.Handler then usage would remain relatively unchanged.

2022-06-09 08:39 UTC, marcusarnemonaviga commented on navigaid/access_test_server.go
> -func NewMockService(opts MockServerOptions) (*http.ServeMux, *rsa.PrivateKey, error) {
Implemented the struct, and adapted all method calls of NewMockService accordingly, unsure how to go about how and where to implement http.Handler

2022-06-20 08:47 UTC, hugowetterberg approved these changes

2022-06-23 11:30 UTC, merged